find_path(JPEG_INCLUDE_DIR jpeglib.h
        PATHS $ENV{REZ_JPEG_ROOT}/include
        NO_DEFAULT_PATH
)

set(JPEG_NAMES ${JPEG_NAMES} jpeg)
find_library(JPEG_LIBRARY
        NAMES ${JPEG_NAMES}
        PATHS $ENV{REZ_JPEG_ROOT}/lib
        NO_DEFAULT_PATH
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(JPEG DEFAULT_MSG JPEG_LIBRARY JPEG_INCLUDE_DIR)

if(JPEG_FIND)
    set(JPEG_LIBRARIES ${JPEG_LIBRARY})
endif()

set(NATIVE_JPEG_INCLUDE_PATH ${JPEG_INCLUDE_DIR})
if(JPEG_LIBRARY)
    get_filename_component(NATIVE_JPEG_LIB_PATH ${JPEG_LIBRARY} PATH)
endif()

mark_as_advanced(JPEG_LIBRARY JPEG_INCLUDE_DIR)
